name: "Frogbot General Scan"
on:
  push:
    branches: ["**"]        # Trigger on every push to every branch
  pull_request_target:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  frogbot-scan:
    runs-on: ubuntu-latest
    environment: frogbot
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Ensures all branches/refs are available.

      - name: Run Frogbot
        uses: jfrog/frogbot@v2
        env:
          # Connection Details
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.JF_GIT_TOKEN }}
          JF_WORKING_DIR: "npm-example"
          JF_WATCHES: "sss-servicenow"
          
          # Branch Configuration
          # This variable tells Frogbot to scan the branch that triggered the action
          JF_GIT_BASE_BRANCH: ${{ github.ref_name }} 
          
          # Scan Settings
          JFROG_CLI_LOG_LEVEL: DEBUG
          JF_INCLUDE_ALL_VULNERABILITIES: "TRUE"
          JF_FAIL: "FALSE"
